# Generated by Django 2.2.24 on 2021-09-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('horario_begin', models.TimeField(null=True)),
                ('horario_end', models.TimeField(null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
